export enum JobCategory {
  QUAY_PHIM = "QUAY_PHIM",
  DUNG_PHIM = "DUNG_PHIM",
  THIET_KE = "THIET_KE",
  AI_CONTENT = "AI_CONTENT",
  MARKETING = "MARKETING",
  BIEN_KICH = "BIEN_KICH",
  KHAC = "KHAC",
}

export enum PerformerType {
  VENDOR = "VENDOR",
  INTERNAL = "INTERNAL",
}

export enum JobLevel {
  A = "A",
  B = "B",
  C = "C",
}

export enum JobResponsibleRole {
  CONTENT_CREATOR = "CONTENT_CREATOR",
  EDITOR = "EDITOR",
  DESIGNER = "DESIGNER",
  CAMERAMAN = "CAMERAMAN",
  ACCOUNT = "ACCOUNT",
  VIDEO_EDITOR = "VIDEO_EDITOR",
  SOCIAL_MEDIA_MANAGER = "SOCIAL_MEDIA_MANAGER",
  PROJECT_MANAGER = "PROJECT_MANAGER",
}
