export enum AcceptanceStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  PROCESSED = "PROCESSED",
}

export enum ContractServiceStatus {
  ACTIVE = "ACTIVE",
  ACCEPTANCE_REJECTED = "ACCEPTANCE_REJECTED",
  CANCELLED = "CANCELLED",
  AWAITING_ACCEPTANCE = "AWAITING_ACCEPTANCE",
  COMPLETED = "COMPLETED",
}
