export enum OpportunityStatus {
  OPEN = "OPEN",
  PENDING_OPP_APPROVAL = "PENDING_OPP_APPROVAL",
  OPP_REJECTED = "OPP_REJECTED",
  OPP_APPROVED = "OPP_APPROVED",
  QUOTATION_DRAFTING = "QUOTATION_DRAFTING",
  PENDING_QUOTE_APPROVAL = "PENDING_QUOTE_APPROVAL",
  QUOTE_APPROVED = "QUOTE_APPROVED",
  CONTRACT_CREATED = "CONTRACT_CREATED",
  CONTRACT_APPROVED = "CONTRACT_APPROVED",
  PROJECT_ASSIGNED = "PROJECT_ASSIGNED",
  IMPLEMENTATION = "IMPLEMENTATION",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum CustomerType {
  DIRECT = "DIRECT",
  REFERRAL = "REFERRAL",
}
