import { Entity, Column, ManyToOne, JoinColumn, Index } from "typeorm";
import { BaseEntity } from "@core/database/base.entity";
import { Project } from "@modules/project/project-core/entities/project.entity";
import { Tasks } from "@modules/project/task/entities/task.entity";
import { Users } from "@modules/identity/user/entities/user.entity";
import { Vendors } from "@modules/crm/vendor/entities/vendor.entity";

export enum PaymentRequestType {
  PROJECT = "PROJECT",
  OTHER_WORK = "OTHER_WORK",
}

export enum PaymentRequestApprovalStatus {
  DRAFT = "DRAFT",
  PENDING_REVIEWER = "PENDING_REVIEWER",
  NEED_MORE_DOCS = "NEED_MORE_DOCS",
  PENDING_BOD = "PENDING_BOD",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}

export enum PaymentDueStatus {
  WAITING = "WAITING",
  DUE_SOON = "DUE_SOON",
  OVERDUE = "OVERDUE",
  PAID = "PAID",
  NOT_APPLICABLE = "NOT_APPLICABLE",
}

export enum PaymentMethod {
  BANK_TRANSFER = "BANK_TRANSFER",
  CASH = "CASH",
}

export interface CashVoucherInfo {
  voucherNo?: string;
  bookNo?: string;
  receiverName?: string;
  receiverAddress?: string;
  reason?: string;
  amount?: number;
  amountInWords?: string;
  debitAccount?: string;
  creditAccount?: string;
  attachmentCount?: number;
  createdDate?: string;
  companyName?: string;
  companyAddress?: string;
}

export interface PaymentRequestFile {
  name: string;
  url: string;
  type?: string;
  size?: number;
  round?: number;
  uploadedAt?: string;
}

export interface PaymentRequestHistoryEntry {
  action:
    | "CREATED"
    | "SUBMITTED"
    | "SUPPLEMENTED"
    | "REVIEWED"
    | "BOD_DECISION"
    | "PAID"
    | "CANCELLED";
  at: string;
  byId: string;
  byName?: string | null;
  note?: string | null;
  snapshot?: {
    content: string;
    amount: number;
    dueDate: string | Date;
    invoiceImages: PaymentRequestFile[];
    invoicePdfs: PaymentRequestFile[];
  };
}

@Entity("payment_requests")
@Index(["approvalStatus", "dueDate"])
@Index(["projectId", "approvalStatus"])
export class PaymentRequests extends BaseEntity {
  @Column({
    type: "enum",
    enum: PaymentRequestType,
  })
  type: PaymentRequestType;

  @Column({ type: "text" })
  content: string;

  @Column({ type: "decimal", precision: 15, scale: 3 })
  amount: number;

  @Column({ type: "date" })
  dueDate: Date;

  @Column({ type: "date", nullable: true })
  confirmedDueDate: Date | null;

  @Column({ type: "varchar", length: 26, nullable: true })
  confirmedDueDateById: string | null;

  @ManyToOne(() => Users, { nullable: true })
  @JoinColumn({ name: "confirmedDueDateById" })
  confirmedDueDateBy: Users | null;

  @Index()
  @Column({ type: "varchar", length: 26, nullable: true })
  projectId: string | null;

  @ManyToOne(() => Project, { nullable: true })
  @JoinColumn({ name: "projectId" })
  project: Project | null;

  @Index()
  @Column({ type: "varchar", length: 26, nullable: true })
  taskId: string | null;

  @ManyToOne(() => Tasks, { nullable: true })
  @JoinColumn({ name: "taskId" })
  task: Tasks | null;

  @Column({ type: "varchar", length: 26, nullable: true })
  vendorId: string | null;

  @ManyToOne(() => Vendors, { nullable: true })
  @JoinColumn({ name: "vendorId" })
  vendor: Vendors | null;

  @Column({ type: "boolean", default: false })
  isAutoGenerated: boolean;

  @Column({ type: "jsonb", default: [] })
  history: PaymentRequestHistoryEntry[];

  @Column({ type: "decimal", precision: 15, scale: 3, nullable: true })
  costPrice: number | null;

  @Column({ type: "jsonb", default: [] })
  invoiceImages: PaymentRequestFile[];

  @Column({ type: "jsonb", default: [] })
  invoicePdfs: PaymentRequestFile[];

  @Index()
  @Column({ type: "varchar", length: 26 })
  requesterId: string;

  @ManyToOne(() => Users)
  @JoinColumn({ name: "requesterId" })
  requester: Users;

  @Index()
  @Column({
    type: "enum",
    enum: PaymentRequestApprovalStatus,
    default: PaymentRequestApprovalStatus.DRAFT,
  })
  approvalStatus: PaymentRequestApprovalStatus;

  @Column({ type: "varchar", length: 26, nullable: true })
  reviewerId: string | null;

  @ManyToOne(() => Users, { nullable: true })
  @JoinColumn({ name: "reviewerId" })
  reviewer: Users | null;

  @Column({ type: "timestamptz", nullable: true })
  reviewedAt: Date | null;

  @Column({ type: "text", nullable: true })
  reviewNote: string | null;

  @Column({ type: "varchar", length: 26, nullable: true })
  submittedToBodById: string | null;

  @ManyToOne(() => Users, { nullable: true })
  @JoinColumn({ name: "submittedToBodById" })
  submittedToBodBy: Users | null;

  @Column({ type: "timestamptz", nullable: true })
  submittedToBodAt: Date | null;

  @Column({ type: "varchar", length: 26, nullable: true })
  bodDecisionById: string | null;

  @ManyToOne(() => Users, { nullable: true })
  @JoinColumn({ name: "bodDecisionById" })
  bodDecisionBy: Users | null;

  @Column({ type: "timestamptz", nullable: true })
  bodDecisionAt: Date | null;

  @Column({ type: "text", nullable: true })
  bodDecisionReason: string | null;

  @Index()
  @Column({
    type: "enum",
    enum: PaymentDueStatus,
    default: PaymentDueStatus.WAITING,
  })
  paymentStatus: PaymentDueStatus;

  @Column({ type: "timestamptz", nullable: true })
  paidAt: Date | null;

  @Column({
    type: "enum",
    enum: PaymentMethod,
    nullable: true,
  })
  paymentMethod: PaymentMethod | null;

  @Column({ type: "jsonb", nullable: true })
  cashVoucherInfo: CashVoucherInfo | null;

  @Column({ type: "jsonb", default: [] })
  paymentProofs: PaymentRequestFile[];
}

export { PaymentRequests as PaymentRequest };
