export enum MemberRole {
  CONTENT_CREATOR = "CONTENT_CREATOR",
  EDITOR = "EDITOR",
  DESIGNER = "DESIGNER",
  CAMERAMAN = "CAMERAMAN",
  ACCOUNT = "ACCOUNT",
  VIDEO_EDITOR = "VIDEO_EDITOR",
  SOCIAL_MEDIA_MANAGER = "SOCIAL_MEDIA_MANAGER",
  PROJECT_MANAGER = "PROJECT_MANAGER",
}
